"""empty message

Revision ID: 106a62cfb887
Revises: 429ca048de5b
Create Date: 2017-08-17 13:39:23.171000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106a62cfb887'
down_revision = '429ca048de5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('location', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'location')
    # ### end Alembic commands ###
